language: java
jdk:
  - oraclejdk8

after_install:
  - gradle setupCIWorkspace
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

deploy:
  - provider: releases
    api_key:
      secure: $GITACCESSTOKEN
    file_glob: true
    file: "./build/libs/*.jar | grep -v obf"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: /bin/sh ./gitwebpages.sh
    skip_cleanup: true
    on:
      tags: true